require(
  [
  '../../test/spec_events',
  '../../test/spec_loading',
  '../../test/spec_views',
  '../../test/coffee/spec_main',
  '../../test/rest-coffee/spec_main',
  '../../test/utils/spec_semanticLink',
  '../../test/utils/spec_httpCall',
  ]
)
